# Site settings
title: Renato Frota - Desenvolvedor Web
description: Site pessoal e blog de um desenvolvedor que adora viajar (de avião e na maionese)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.renatofrota.com" # the base protocol & hostname for your site

# User settings
username: renatofrota
user_description: Desenvolvedor Web
email: renatofrota@gmail.com
twitter_username: Renato_Frota
github_username: renatofrota
gplus_username: +RenatoFrota
disqus_subdomain: "renato-frota" # it's not the username, it's the subdomain of your "Site"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Séries
    url: /series
  - title: Tags
    url: /tags
  - title: Sobre mim
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
